### ISSUE TITLE
速度还是有点慢

### ISSUE THREAD

**Issue by zhuzhu18** [zhoumumu/VapSR#5]
虽然参数量少，但推理速度还是太慢了，转成tensorrt后在同样的机器上，360p的输入只有50多fps，vapsr-s版本也只有80多fps，RFDN的速度可以达到130fps左右

**Comment by zhoumumu** [comment]
1.RFDN的特点是它的分支结构，模型复杂度很高(params, multi-adds)，并且分支汇总时要等到四个卷积输出，四个输出同时呆在内存里会产生非常卡脖子的内存占用。以上，用模型复杂度和空间复杂度换低时间复杂度是很自然的。

2.这个分支结构在正常运算时是个很致命的停等结构，但tensorrt的并行优化可以化解这一点，进一步提升了推理时间。同理，这一步的代价是，你的tensorrt模型要部署的话，需要额外安装推理引擎，在某些移动端上可能比较有负担。

3.我们的模型显然是在模型复杂度和空间复杂度上表现更为亮眼。如何综合各个维度来评价模型可以参看去年的[竞赛报告](https://arxiv.org/pdf/2205.05675.pdf)，如果你只关心推理时间那么可以找主赛道第一名。事实上，去年主赛道第一就用了剪枝的模型压缩方法来提速，我们这种简洁的卷积结构同样很适合压缩，比如可以考虑用通道剪枝进一步提速。
