### ISSUE TITLE
Parameters of the model,

### ISSUE THREAD

**Issue by Sabermu** [zhoumumu/VapSR#6]
Hello author, I like your work very much, but now I have a problem. I used the profile to calculate the Parameters of the model, but in the case of X4, the calculated value is 440K. Is my calculation method wrong? Please advise, thank you

**Comment by zhoumumu** [comment]
Let's compare our log info to find the difference.

[train_VapSR_betaX4_20220801_005233.log](https://github.com/zhoumumu/VapSR/files/11541917/train_VapSR_betaX4_20220801_005233.log)
