### ISSUE TITLE
 confusion about layer normalization and pixel normalization

### ISSUE THREAD

**Issue by recallwolf** [zhoumumu/VapSR#7]
您好我注意到您论文提出的像素归一化在代码中的实现如下：
`self.pixel_norm = nn.LayerNorm(d_model)`

我查询layer norm的公式和您论文中提供的公式非常相似，我可以不可以认为pixel norm和layer norm是一个等价关系？

非常感谢您提供的代码

**Comment by zhoumumu** [comment]
不一样的，pixelnorm的实现不止一个声明语句，还有后面的调用
```
x = x.permute(0, 2, 3, 1) #(B, H, W, C)
x = self.pixel_norm(x)
x = x.permute(0, 3, 1, 2).contiguous() #(B, C, H, W)
```
